# Build stage
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production stage
FROM node:22-alpine AS production

WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

COPY --from=build /app/dist ./dist
COPY drizzle.config.ts ./
COPY src/db ./src/db

EXPOSE 2001

CMD npx drizzle-kit push && node dist/src/main.js
